### ISSUE TITLE
Management Interface shouldn't show features to users without permissions

### ISSUE THREAD

**Issue by BurningDog** [cloudamqp/lavinmq#598] opened 2023-11-16 10:03 UTC
I've added a new user and given them the `monitoring` tag only. I've not given them access to my single `vhost` I've added, and have given them no additional permissions.

When I log in as that user I have admin permissions. I can add and delete exchanges, queues, and users. Instead, I expect that I would only be able to view metrics and not perform any admin tasks.

**Comment by BurningDog** [comment] 2023-11-16 10:13
I've also added permission to a vhost and added regex which matches nothing - `r"^$"` - to the config and write permissions - and I can still act as an admin with that user.

**Comment by viktorerlingsson** [comment] 2023-11-16 10:47
Hi @BurningDog , thanks for reporting. We've tried, but haven't been able to reproduce this ourselves yet. 
Could you please provide your `users.json` file? It should be in the root of your data directory (default `/var/lib/lavinmq/users.json`).

**Comment by BurningDog** [comment] 2023-11-16 10:56
Ah - my mistake - I hadn't _actually_ continued with deleting the exchange, as I expected that if I don't have permissions to delete an exchange, then there should be no "Delete exchange" button visible. I get an access denied message if I try.

I expected that anything to do with add/edit/delete would _not_ be visible to a `monitoring` user - it's confusing to show this functionality when it's not accessible (this includes the links in the sidebar: `Virtual hosts`, `Users`, etc).

**Comment by viktorerlingsson** [comment] 2023-11-16 11:21
Okay, good to hear that it's working as expected in the end!

**Comment by dentarg** [comment] 2023-11-16 14:27
Do we want to address this? I guess it would require more round-trips to the backend or duplicating permission logic in the UI?

**Comment by viktorerlingsson** [comment] 2023-11-16 15:19
> Do we want to address this? I guess it would require more round-trips to the backend or duplicating permission logic in the UI (client side code)?

I'm planning on raising it for discussion on our next team meeting. But I don't think it's something we want to change at the moment, since I think it's a pretty low priority thing.

**Comment by viktorerlingsson** [comment] 2023-11-21 10:25
We've discussed this in the team, and decided we will not do this at the moment. It requires a pretty big change, and we don't think that this is a high enough priority task. We have forwarded it to the UX team though, and it will be taken into consideration when doing future UI updates. 

Closing this as not planned.

**Closed by viktorerlingsson** 2023-11-21 10:25 UTC
